# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for project
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  target 'projectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
